# {{SERVICE_NAME}} Apollo Configuration

apollo {
  logIncomingRequests: false
  logOutgoingRequests: false
}

grpc.server {
  port: 5990
  metrics.enabled: true
  deadlineEnforcer.enabled: true
  reflection.enabled: true
}

http.server {
  port: 8080
  cors {
    origins: ["https://backstage.spotify.net"]
  }
}
