# {{SERVICE_NAME}} Apollo Configuration - With Database

apollo {
  logIncomingRequests: false
  logOutgoingRequests: false
}

grpc.server {
  port: 5990
  metrics.enabled: true
  deadlineEnforcer.enabled: true
  reflection.enabled: true
}

http.server {
  port: 8080
}

jdbc {
  url: "jdbc:postgresql://localhost:5433/{{DATABASE_NAME}}"
  url: ${?POSTGRES_JDBC_URL}
  pool: {
    max-total: 20
    min-idle: 2
  }
}

# Secret injection
jdbc: { include file("/etc/spotify/secrets/{{SERVICE_NAME}}.json") }
