# {{SERVICE_NAME}} Apollo Configuration - gRPC Focused

apollo {
  logIncomingRequests: false
  logOutgoingRequests: false
}

grpc.server {
  port: 5990
  metrics.enabled: true
  deadlineEnforcer.enabled: true
  reflection.enabled: true
}

grpc.client {
  useForkJoinPool: true
  executorThreads: 8
  els {
    enabled: true
    orca.enabled: true
  }
}

hermes.client {
  outstandingRequestLimit: 800
}

http.server {
  port: 8080
}
