apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{SERVICE_NAME}}
    role: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
      annotations:
        apollo.prometheus.spotify.net/scrape: "true"
        podpreset.admission.spotify.com/exclude: "observability"
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: $DEPLOYMENT_IMAGE
          ports:
            - name: grpc
              containerPort: 5990
            - name: http
              containerPort: 8080
            - name: hm
              containerPort: 5700
            - name: hm-snoop
              containerPort: 5701
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "6"
              memory: "8Gi"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5700
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /liveness
              port: 5700
            initialDelaySeconds: 30
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
